name: "Request a New Resource, Data Source, or ONTAP Service"
description: "Choose this option to request an entirely new resource, data source, or ONTAP service be added to the provider."
title: "[New]: "
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening a request!

        This form is intended to be used when requesting an entirely new resource, data source, or service be added to the provider. If you're looking for a change to be made to an existing resource or data source, consider submitting either the "Request an Enhancement" or Report a Bug" forms instead.

        When possible, it's helpful to check the [ONTAP REST API](https://library.netapp.com/ecmdocs/ECMLP2885799/html/index.html) to determine whether functionality exists to enable the requested feature. It is **not** required that you do this. Any references found when searching can be added to the "References" field below to give maintainers or the community a head start.

        Please update the title to match what you're requesting, e.g.:

        - `[New Resource]:` - for new resource requests
        - `[New Data Source]:` - for new data source requests
        - `[New Service]:` - for new ONTAP services
        
        Please add a label on the right to match what your requesting, e.g.:
        
        - `New Resource` - for new resource requests
        - `New Data Source` - for new data source requests

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please leave a brief description of what you're requesting.
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Requested Resource(s) and/or Data Source(s)
      description: |
        Please list any new resource(s) and/or data source(s). The naming format is `ONTAP_<service>_<resource_name>`, e.g., `ONTAP_lambda_function`.

        A best guess is helpful, even if you're unsure of exactly what the end result will look like. This helps maintainers and the community better understand how you (someone who is in need of this request) envisions it.
      placeholder: "* netapp_ontap_xxx_yyy"
    validations:
      required: true

  - type: textarea
    id: tf_config
    attributes:
      label: Potential Terraform Configuration
      description: |
        If this request was implemented, what might the Terraform configuration look like? Similar to above, a best guess is helpful, even if you're unsure of exactly what the end result will look like.

        **Note:** This field will render in HCL, so there is no need to add a [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: terraform
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false

  - type: dropdown
    id: will_contribute
    attributes:
      label: Would you like to implement a fix?
      description: |
        If you plan to implement a fix for this, check this box to let the maintainers and community know (you can update this later if you change your mind). If this would be your first contribution, refer to the ::TODO:: [contribution guide](https://hashicorp.github.io/terraform-provider-ONTAP/) for tips on getting started.
      options:
        - "No"
        - "Yes"
    validations:
      required: false