name: Go ACC Tests

on: [push]

jobs:
  build:

    runs-on: self-hosted
    concurrency:
      group: ONTAP-ACC
      cancel-in-progress: false
    # because Dependabot dosn't get access to secrets, and we don't need it to run our ACC TEST, let skip them for that user
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.3'

      - name: Build
        env:
          TF_ACC_NETAPP_HOST: ${{ secrets.TF_ACC_NETAPP_HOST }}
          TF_ACC_NETAPP_HOST2: ${{ secrets.TF_ACC_NETAPP_HOST2 }}
          TF_ACC_NETAPP_HOST3: ${{ secrets.TF_ACC_NETAPP_HOST3 }}
          TF_ACC_NETAPP_HOST4: ${{ secrets.TF_ACC_NETAPP_HOST4 }}
          TF_ACC_NETAPP_HOST_CIFS: ${{ secrets.TF_ACC_NETAPP_HOST_CIFS }}
          TF_ACC_NETAPP_USER: ${{ secrets.TF_ACC_NETAPP_USER }}
          TF_ACC_NETAPP_PASS: ${{ secrets.TF_ACC_NETAPP_PASS }}
          TF_ACC_NETAPP_PASS2: ${{ secrets.TF_ACC_NETAPP_PASS2 }}
          TF_ACC_NETAPP_PASS_CIFS: ${{ secrets.TF_ACC_NETAPP_PASS_CIFS }}
          TF_ACC_NETAPP_LICENSE: ${{ secrets.TF_ACC_NETAPP_LICENSE }}

        run: |
          export GOFLAGS=-buildvcs=false
          export TF_ACC=1
          go test `go list ./... | grep -e provider`
