name: Go ACC Tests

on: 
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "integration/main" ]

jobs:
  build:

    runs-on: self-hosted
    concurrency:
      group: ONTAP-ACC
      cancel-in-progress: false
    # because Dependabot dosn't get access to secrets, and we don't need it to run our ACC TEST, let skip them for that user
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Detect changed resource files
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep '^provider/.*resource.*\.go$')
          echo "Changed resource files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Build
        env:
          TF_ACC_NETAPP_HOST: ${{ secrets.TF_ACC_NETAPP_HOST }}
          TF_ACC_NETAPP_HOST2: ${{ secrets.TF_ACC_NETAPP_HOST2 }}
          TF_ACC_NETAPP_HOST3: ${{ secrets.TF_ACC_NETAPP_HOST3 }}
          TF_ACC_NETAPP_HOST4: ${{ secrets.TF_ACC_NETAPP_HOST4 }}
          TF_ACC_NETAPP_HOST5: ${{ secrets.TF_ACC_NETAPP_HOST5 }}
          TF_ACC_NETAPP_HOST_CIFS: ${{ secrets.TF_ACC_NETAPP_HOST_CIFS }}
          TF_ACC_NETAPP_USER: ${{ secrets.TF_ACC_NETAPP_USER }}
          TF_ACC_NETAPP_PASS: ${{ secrets.TF_ACC_NETAPP_PASS }}
          TF_ACC_NETAPP_PASS2: ${{ secrets.TF_ACC_NETAPP_PASS2 }}
          TF_ACC_NETAPP_PASS_CIFS: ${{ secrets.TF_ACC_NETAPP_PASS_CIFS }}
          TF_ACC_NETAPP_LICENSE: ${{ secrets.TF_ACC_NETAPP_LICENSE }}
          TF_ACC_NETAPP_CIFS_ADDOMAIN_PASS: ${{ secrets.TF_ACC_NETAPP_CIFS_ADDOMAIN_PASS }}
        run: |
          export GOFLAGS=-buildvcs=false
          export TF_ACC=1
          export TMPDIR=~/tmp/
          for FILE in ${{ steps.changes.outputs.changed_files }}; do
            DIR=$(dirname "$FILE")
            go test "$DIR/..."
          done

      - name: Cleanup
        if: always()
        run: |
          rm -rf ~/tmp/
