name: Go ACC Tests

on: 
  push:
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches: [ "integration/main" ]

jobs:
  build:

    runs-on: self-hosted
    concurrency:
      group: ONTAP-ACC
      cancel-in-progress: false
    # because Dependabot dosn't get access to secrets, and we don't need it to run our ACC TEST, let skip them for that user
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Detect changed resource files
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          else
            BASE_BRANCH=integration/main
          fi
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH | grep -E '.*resource.go$|.*provider.*test.go$' || true)
          INTERFACE_FILES=$(git diff --name-only origin/$BASE_BRANCH | grep -E '.*interfaces.*.go$' || true)
          if [ -z "$CHANGED_FILES" ] && [ -z "$INTERFACE_FILES" ]; then
            echo "No resource, test, or interface files changed."
            echo "changed_files=" >> $GITHUB_ENV
            echo "interface_files=" >> $GITHUB_ENV
            exit 0
          fi
          UPDATED_CHANGED_FILES=""
          for FILE in $changed_files; do
            if [[ "$FILE" == *resource.go ]]; then
              TEST_FILE="${FILE%.go}_test.go"
            else
              TEST_FILE="$FILE"
            fi
            UPDATED_CHANGED_FILES="$UPDATED_CHANGED_FILES $TEST_FILE"
          done
          for FILE in $(echo $INTERFACE_FILES | tr ' ' '\n'); do
            if [[ "$FILE" == *test.go ]] || [[ "$FILE" == *cluster_job.go ]]; then
              continue
            fi
            BASE_NAME=$(basename "$FILE")
            if [[ "$BASE_NAME" == *name_services* ]]; then
              PREFIX=$(echo "$BASE_NAME" | awk -F'_' '{print $1"_"$2}')
            else
              PREFIX=${BASE_NAME%%_*}
            fi
            TEST_FILE="internal/provider/${PREFIX}/${BASE_NAME%.go}_resource_test.go"
            if ! echo "$UPDATED_CHANGED_FILES" | grep -q "$TEST_FILE"; then
              UPDATED_CHANGED_FILES="$UPDATED_CHANGED_FILES $TEST_FILE"
            fi
          done
          printf "Acceptance test files required to run: %b\n" "$UPDATED_CHANGED_FILES"
          printf "INTERFACE_FILES: %b\n" "$INTERFACE_FILES"
          echo "Changed resource files: $UPDATED_CHANGED_FILES"
          echo "UPDATED_CHANGED_FILES=$UPDATED_CHANGED_FILES" >> $GITHUB_ENV

      - name: Create temporary directory
        run: mkdir -p ~/tmp/

      - name: Build
        if: env.UPDATED_CHANGED_FILES != ''
        env:
          TF_ACC_NETAPP_HOST: ${{ secrets.TF_ACC_NETAPP_HOST }}
          TF_ACC_NETAPP_HOST2: ${{ secrets.TF_ACC_NETAPP_HOST2 }}
          TF_ACC_NETAPP_HOST3: ${{ secrets.TF_ACC_NETAPP_HOST3 }}
          TF_ACC_NETAPP_HOST4: ${{ secrets.TF_ACC_NETAPP_HOST4 }}
          TF_ACC_NETAPP_HOST5: ${{ secrets.TF_ACC_NETAPP_HOST5 }}
          TF_ACC_NETAPP_HOST_CIFS: ${{ secrets.TF_ACC_NETAPP_HOST_CIFS }}
          TF_ACC_NETAPP_USER: ${{ secrets.TF_ACC_NETAPP_USER }}
          TF_ACC_NETAPP_PASS: ${{ secrets.TF_ACC_NETAPP_PASS }}
          TF_ACC_NETAPP_PASS2: ${{ secrets.TF_ACC_NETAPP_PASS2 }}
          TF_ACC_NETAPP_PASS_CIFS: ${{ secrets.TF_ACC_NETAPP_PASS_CIFS }}
          TF_ACC_NETAPP_LICENSE: ${{ secrets.TF_ACC_NETAPP_LICENSE }}
          TF_ACC_NETAPP_CIFS_ADDOMAIN_PASS: ${{ secrets.TF_ACC_NETAPP_CIFS_ADDOMAIN_PASS }}
        run: |
          export GOFLAGS=-buildvcs=false
          export TF_ACC=1
          export TMPDIR=~/tmp/
          for FILE in $UPDATED_CHANGED_FILES; do
            printf "Acceptance test for %s is running\n" "$FILE"
            go test "$FILE"
          done

      - name: Cleanup
        if: always()
        run: |
          rm -rf ~/tmp/
