name: Blackduck Scan

on:
  push:
    branches:
      - integration/main

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build
        env:
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
          BLACKDUCK_API_TOKEN: ${{ secrets.$BLACKDUCK_API_TOKEN }}

        run: |
          bash pipeline_scripts/bd_scan.bash $BLACKDUCK_URL $BLACKDUCK_API_TOKEN
