name: Blackduck Scan

on:
  push:
    branches:
      - integration/main

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3

      - name: Build
        env:
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

        run: |
          bash scripts/bd_scan.bash $BLACKDUCK_URL $BLACKDUCK_API_TOKEN
