name: Check for Missing Documentation

on:
  pull_request:
    branches: [ "integration/main" ]

jobs:
  check-missing-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for missing .md files
        run: |
          MISSING_DOCS=""
          RESOURCE_FILES=$(find . -type f -name '*_resource.go')
          for FILE in $RESOURCE_FILES; do
            DOC_FILE="${FILE##*/}"
            DOC_FILE="${DOC_FILE/_resource.go/.md}"
            DOC_FILE="docs/resources/$DOC_FILE"
            if [ ! -f "$DOC_FILE" ]; then
              MISSING_DOCS="$MISSING_DOCS\n$DOC_FILE"
            fi
          done
          if [ -n "$MISSING_DOCS" ]; then
            echo "The following documentation files are missing:$MISSING_DOCS"
            exit 1
          else
            echo "All resource files have corresponding documentation."
          fi
      
       - name: Check for missing .md files
        run: |
          MISSING_DOCS=""
          RESOURCE_FILES=$(find . -type f -name '*_resource.go')
          DATA_SOURCE_FILES=$(find . -type f -name '*_data_source.go')
          
          for FILE in $RESOURCE_FILES; do
            DOC_FILE="${FILE##*/}"
            DOC_FILE="${DOC_FILE/_resource.go/.md}"
            DOC_FILE="docs/resources/$DOC_FILE"
            if [ ! -f "$DOC_FILE" ]; then
              MISSING_DOCS="$MISSING_DOCS\n$DOC_FILE"
            fi
          done

          for FILE in $DATA_SOURCE_FILES; do
            DOC_FILE="${FILE##*/}"
            DOC_FILE="${DOC_FILE/_data_source.go/.md}"
            DOC_FILE="docs/data-sources/$DOC_FILE"
            if [ ! -f "$DOC_FILE" ]; then
              MISSING_DOCS="$MISSING_DOCS\n$DOC_FILE"
            fi
          done

          if [ -n "$MISSING_DOCS" ]; then
            echo "The following documentation files are missing:$MISSING_DOCS"
            exit 1
          else
            echo "All resource and data source files have corresponding documentation."
          fi