name: Check Missing Parameters in Documentation

on:
  pull_request:
    paths:
      - 'internal/provider/**/*.go'
      - 'docs/data-sources/*.md'
      - 'docs/resources/*.md'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find missing parameters
        id: check
        run: |
          # Find all resource files
          RESOURCE_FILES=$(find internal/provider -name '*resource.go')

          # Extract parameters from all resource files
          RESOURCE_PARAMS=""
          for FILE in $RESOURCE_FILES; do
            PARAMS=$(grep -oP '"\K\w+(?=": schema\.\w+Attribute)' $FILE)
            RESOURCE_PARAMS="$RESOURCE_PARAMS\n$PARAMS"
          done
          RESOURCE_PARAMS=$(echo -e "$RESOURCE_PARAMS" | sort | uniq)

          # Extract parameters from the documentation files
          DOC_FILES=$(find docs/data-sources docs/resources -name '*.md')
          DOC_PARAMS=$(grep -hoP '^\s*-\s+`\K\w+(?=`)' $DOC_FILES | sort | uniq)

          # Find missing parameters
          MISSING_PARAMS=$(comm -23 <(echo "$RESOURCE_PARAMS") <(echo "$DOC_PARAMS"))

          # Output missing parameters
          if [ -n "$MISSING_PARAMS" ]; then
            echo "Missing parameters in documentation:"
            echo "$MISSING_PARAMS"
            echo "::set-output name=missing::$MISSING_PARAMS"
            exit 1
          else
            echo "No missing parameters in documentation."
          fi