name: Go Lint

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "integration/main" ]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
