name: Go Unit Tests

on:
  push:
    branches:
      - "integration/main"
      - "stable*"
  pull_request:
    branches:
      - "integration/main"
      - "stable*"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: |
          export GOFLAGS=-buildvcs=false
          ./scripts/unittest.sh
