name: Go Unit Tests

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "integration/main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: |
          export GOFLAGS=-buildvcs=false
          ./scripts/unittest.sh
